# Generated by Django 5.2.11 on 2026-02-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The access code/card number', max_length=100, unique=True)),
                ('code_type', models.CharField(choices=[('RFID', 'RFID Card'), ('PIN', 'PIN Code'), ('BIOMETRIC', 'Biometric'), ('OTHER', 'Other')], default='RFID', help_text='Type of access code', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code is active')),
                ('issued_date', models.DateField(auto_now_add=True, help_text='Date when code was issued')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Code',
                'verbose_name_plural': 'Access Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Access point name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code identifier', max_length=20, unique=True)),
                ('access_type', models.CharField(choices=[('MAIN_GATE', 'Main Gate'), ('PEDESTRIAN', 'Pedestrian Door'), ('VEHICLE', 'Vehicle Gate'), ('BUILDING_DOOR', 'Building Door'), ('GARAGE', 'Garage'), ('POOL', 'Pool/Amenities'), ('GYM', 'Gym'), ('OTHER', 'Other')], default='MAIN_GATE', help_text='Type of access point', max_length=20)),
                ('location', models.CharField(help_text='Physical location description', max_length=200)),
                ('supports_qr', models.BooleanField(default=True, help_text='Supports QR code scanning')),
                ('supports_rfid', models.BooleanField(default=False, help_text='Supports RFID card reading')),
                ('supports_numeric', models.BooleanField(default=True, help_text='Supports numeric code entry')),
                ('is_entry', models.BooleanField(default=True, help_text='Is this an entry point')),
                ('is_exit', models.BooleanField(default=True, help_text='Is this an exit point')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this access point is active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Point',
                'verbose_name_plural': 'Access Points',
                'ordering': ['name'],
            },
        ),
    ]
