# Generated by Django 5.2.11 on 2026-02-18 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='resident',
            field=models.ForeignKey(help_text='Resident this code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='residents.resident'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Associated building (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_points', to='residents.building'),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='access_points',
            field=models.ManyToManyField(blank=True, help_text='Access points where this code is valid', related_name='allowed_codes', to='access_control.accesspoint'),
        ),
    ]
