# Generated by Django 5.2.11 on 2026-02-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Name of person accessing', max_length=200)),
                ('person_document', models.CharField(blank=True, help_text='Document ID of person', max_length=50)),
                ('access_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default='ENTRY', help_text='Type of access (entry/exit)', max_length=20)),
                ('access_method', models.CharField(choices=[('QR_CODE', 'QR Code'), ('RFID', 'RFID Card'), ('NUMERIC_CODE', 'Numeric Code'), ('ALPHANUMERIC_CODE', 'Alphanumeric Code'), ('MANUAL', 'Manual Entry'), ('BIOMETRIC', 'Biometric'), ('OTHER', 'Other')], help_text='Method used to access', max_length=30)),
                ('code_used', models.CharField(blank=True, help_text='Code or credential used', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('ERROR', 'Error')], default='SUCCESS', help_text='Access status', max_length=20)),
                ('denial_reason', models.TextField(blank=True, help_text='Reason for denial (if denied)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the access occurred')),
                ('vehicle_plate', models.CharField(blank=True, help_text='Vehicle plate (if applicable)', max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature reading (if applicable)', max_digits=4, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo taken at access point', null=True, upload_to='logs/photos/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of access point device', null=True)),
                ('device_id', models.CharField(blank=True, help_text='Device identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_code', models.ForeignKey(blank=True, help_text='Permanent access code used (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='access_control.accesscode')),
                ('access_point', models.ForeignKey(help_text='Access point used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='access_control.accesspoint')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
