# Generated by Django 5.2.11 on 2026-02-18 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_logs', '0001_initial'),
        ('residents', '0001_initial'),
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='Guard who authorized (for manual entry)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='resident',
            field=models.ForeignKey(blank=True, help_text='Resident (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='residents.resident'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='temporary_code',
            field=models.ForeignKey(blank=True, help_text='Temporary code used (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='visitors.temporarycode'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='Visitor (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='visitors.visitor'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['-timestamp'], name='access_logs_timesta_9b4166_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['resident', '-timestamp'], name='access_logs_residen_23e2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['visitor', '-timestamp'], name='access_logs_visitor_16b077_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_point', '-timestamp'], name='access_logs_access__9d49ac_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['status', '-timestamp'], name='access_logs_status_f95292_idx'),
        ),
    ]
