# Generated by Django 5.2.11 on 2026-02-18 19:05

import django.db.models.deletion
import django.utils.timezone
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Visitor first name', max_length=100)),
                ('last_name', models.CharField(help_text='Visitor last name', max_length=100)),
                ('document_id', models.CharField(blank=True, help_text='ID document number', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[utils.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('photo', models.ImageField(blank=True, help_text='Visitor photo', null=True, upload_to='visitors/photos/')),
                ('visitor_type', models.CharField(choices=[('GUEST', 'Guest'), ('DELIVERY', 'Delivery'), ('SERVICE', 'Service Provider'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], default='GUEST', help_text='Type of visitor', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('DENIED', 'Denied')], default='PENDING', help_text='Current status', max_length=20)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of visit')),
                ('expected_date', models.DateField(help_text='Expected date of visit')),
                ('expected_time', models.TimeField(blank=True, help_text='Expected time of arrival', null=True)),
                ('vehicle_plate', models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Company name (for delivery/service)', max_length=200)),
                ('check_in_time', models.DateTimeField(blank=True, help_text='Actual check-in time', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Actual check-out time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, help_text='User who authorized this visitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_visitors', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, help_text='Resident being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='residents.resident')),
                ('unit', models.ForeignKey(help_text='Unit being visited', on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='residents.unit')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The access code', max_length=100, unique=True)),
                ('code_type', models.CharField(choices=[('NUMERIC', 'Numeric Code'), ('ALPHANUMERIC', 'Alphanumeric Code'), ('QR', 'QR Code'), ('OTP', 'One-Time Password')], default='ALPHANUMERIC', help_text='Type of code', max_length=20)),
                ('qr_code_image', models.ImageField(blank=True, help_text='QR code image', null=True, upload_to='codes/qr/')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for OTP generation', max_length=100)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Code valid from this time')),
                ('valid_until', models.DateTimeField(help_text='Code expires at this time')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this code can be used')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code is active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this code was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who generated this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(help_text='Visitor this code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='visitors.visitor')),
            ],
            options={
                'verbose_name': 'Temporary Code',
                'verbose_name_plural': 'Temporary Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
