# Generated by Django 5.2.11 on 2026-02-18 19:05

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Building name or identifier', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the building (e.g., A, B, T1)', max_length=10, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the building')),
                ('floors', models.PositiveIntegerField(default=1, help_text='Number of floors in the building')),
                ('units_per_floor', models.PositiveIntegerField(default=1, help_text='Number of units per floor')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this building is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('document_id', models.CharField(help_text='ID document number', max_length=50, unique=True)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20, validators=[utils.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('photo', models.ImageField(blank=True, help_text='Resident photo', null=True, upload_to='residents/photos/')),
                ('resident_type', models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant'), ('FAMILY', 'Family Member')], default='OWNER', help_text='Type of resident', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact name', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=20, validators=[utils.validators.validate_phone_number])),
                ('is_authorized', models.BooleanField(default=True, help_text='Whether resident has access authorization')),
                ('move_in_date', models.DateField(blank=True, help_text='Date when resident moved in', null=True)),
                ('move_out_date', models.DateField(blank=True, help_text='Date when resident moved out', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Unit number (e.g., 101, 2A, PH1)', max_length=10, validators=[utils.validators.validate_unit_number])),
                ('floor', models.PositiveIntegerField(help_text='Floor number')),
                ('owner_name', models.CharField(blank=True, help_text='Name of the unit owner', max_length=200)),
                ('owner_phone', models.CharField(blank=True, help_text='Owner contact phone', max_length=20, validators=[utils.validators.validate_phone_number])),
                ('is_occupied', models.BooleanField(default=True, help_text='Whether this unit is currently occupied')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['building', 'floor', 'number'],
            },
        ),
    ]
