# Generated by Django 5.2.11 on 2026-02-18 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(help_text='Building this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='residents.building'),
        ),
        migrations.AddField(
            model_name='resident',
            name='unit',
            field=models.ForeignKey(help_text='Unit where resident lives', on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residents.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('building', 'number')},
        ),
    ]
